name: da_movie_quizz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  velocity_x: ^4.2.1
  gap: ^3.0.1

  # state management
  flutter_bloc: ^8.1.6

  # persistence
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1

  #services
  http: ^1.2.2

  #tools
  flutter_dotenv: ^5.1.0

  #functional programing
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env